# Generated by Django 3.1.5 on 2021-01-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='StudyDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SectionCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('text_content', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stibackend.course')),
                ('section_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stibackend.sectioncourse')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stibackend.studydomain'),
        ),
    ]
