# Generated by Django 3.1.5 on 2021-02-01 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stibackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='text_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='stibackend.studydomain'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sectioncourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_courses', to='stibackend.course'),
        ),
        migrations.AlterField(
            model_name='sectioncourse',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studydomain',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
