# Generated by Django 3.1.5 on 2021-02-01 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stibackend', '0003_chapter_courseinscription_partchapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRessource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ressource_type', models.CharField(choices=[('video', 'video'), ('document', 'document')], max_length=40)),
                ('ressource_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Notion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text_content', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_chapters', to='stibackend.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='URLRessource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('notion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls_ressources', to='stibackend.notion')),
            ],
        ),
        migrations.RemoveField(
            model_name='sectioncourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='sectioncourse',
            name='section_parent',
        ),
        migrations.DeleteModel(
            name='PartChapter',
        ),
        migrations.DeleteModel(
            name='SectionCourse',
        ),
        migrations.AddField(
            model_name='fileressource',
            name='notion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_ressources', to='stibackend.notion'),
        ),
    ]
