# Generated by Django 3.1.5 on 2021-02-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stibackend', '0004_auto_20210201_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_file',
        ),
    ]
